WellCommerce\Bundle\ClientBundle\Entity\ClientGroup:
    type: entity
    table: client_group
    repositoryClass: WellCommerce\Bundle\ClientBundle\Repository\ClientGroupRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        discount:
            type: decimal
            scale: 2
            length: null
            unique: false
            nullable: false
            precision: 15
    oneToMany:
        clients:
            targetEntity: WellCommerce\Bundle\ClientBundle\Entity\Client
            fetch: LAZY
            mappedBy: clientGroup
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    manyToMany:
        pages:
            targetEntity: WellCommerce\Bundle\PageBundle\Entity\Page
            fetch: LAZY
            mappedBy: clientGroups
