doctrine:
    orm:
        resolve_target_entities:
            WellCommerce\Bundle\ClientBundle\Entity\ClientInterface: WellCommerce\Bundle\ClientBundle\Entity\Client

well_commerce_client:
    configuration:
        client:
            orm:
                factory: WellCommerce\Bundle\ClientBundle\Factory\ClientFactory
                repository: WellCommerce\Bundle\ClientBundle\Repository\ClientRepository
                mapping: "@WellCommerceClientBundle/Resources/config/doctrine/Client.orm.yml"
                entity: WellCommerce\Bundle\ClientBundle\Entity\Client
            api:
                exposed: true
                dataset: client.dataset.admin
                manager: client.manager
        client_billing_address:
            orm:
                factory: WellCommerce\Bundle\ClientBundle\Factory\ClientBillingAddressFactory
                mapping: "@WellCommerceClientBundle/Resources/config/doctrine/ClientBillingAddress.orm.yml"
                entity: WellCommerce\Bundle\ClientBundle\Entity\ClientBillingAddress
        client_details:
            orm:
                factory: WellCommerce\Bundle\ClientBundle\Factory\ClientDetailsFactory
                mapping: "@WellCommerceClientBundle/Resources/config/doctrine/ClientDetails.orm.yml"
                entity: WellCommerce\Bundle\ClientBundle\Entity\ClientDetails
        client_contact_details:
            orm:
                factory: WellCommerce\Bundle\ClientBundle\Factory\ClientContactDetailsFactory
                mapping: "@WellCommerceClientBundle/Resources/config/doctrine/ClientContactDetails.orm.yml"
                entity: WellCommerce\Bundle\ClientBundle\Entity\ClientContactDetails
        client_group:
            orm:
                factory: WellCommerce\Bundle\ClientBundle\Factory\ClientGroupFactory
                repository: WellCommerce\Bundle\ClientBundle\Repository\ClientGroupRepository
                mapping: "@WellCommerceClientBundle/Resources/config/doctrine/ClientGroup.orm.yml"
                entity: WellCommerce\Bundle\ClientBundle\Entity\ClientGroup
            api:
                exposed: true
                dataset: client_group.dataset.admin
                manager: client_group.manager
        client_group_translation:
            orm:
                mapping: "@WellCommerceClientBundle/Resources/config/doctrine/ClientGroupTranslation.orm.yml"
                entity: WellCommerce\Bundle\ClientBundle\Entity\ClientGroupTranslation
        client_shipping_address:
            orm:
                factory: WellCommerce\Bundle\ClientBundle\Factory\ClientShippingAddressFactory
                mapping: "@WellCommerceClientBundle/Resources/config/doctrine/ClientShippingAddress.orm.yml"
                entity: WellCommerce\Bundle\ClientBundle\Entity\ClientShippingAddress
        client_wishlist:
            orm:
                manager: WellCommerce\Bundle\ClientBundle\Manager\ClientWishlistManager
                factory: WellCommerce\Bundle\ClientBundle\Factory\ClientWishlistFactory
                repository: WellCommerce\Bundle\ClientBundle\Repository\ClientWishlistRepository
                mapping: "@WellCommerceClientBundle/Resources/config/doctrine/ClientWishlist.orm.yml"
                entity: WellCommerce\Bundle\ClientBundle\Entity\ClientWishlist
