WellCommerce\Bundle\ClientBundle\Entity\Client:
    fields:
        id:
            groups:
                - default
                - client
        clientDetails:
            groups:
                - default
                - client
        billingAddress:
            groups:
                - default
                - client
        shippingAddress:
            groups:
                - default
                - client
        contactDetails:
            groups:
                - default
                - client
    associations:
        clientGroup:
            groups:
                - client
        shop:
            groups:
                - client
