WellCommerce\Bundle\ClientBundle\Entity\ClientGroup:
    fields:
        id:
            groups:
                - default
                - client_group
        discount:
            groups:
                - client_group
    associations:
        translations:
            groups:
                - client_group
