WellCommerce\Bundle\ClientBundle\Entity\ClientBillingAddress:
    fields:
        firstName:
            groups:
                - default
                - client_billing_address
        lastName:
            groups:
                - default
                - client_billing_address
        line1:
            groups:
                - default
                - client_billing_address
        line2:
            groups:
                - default
                - client_billing_address
        postalCode:
            groups:
                - default
                - client_billing_address
        state:
            groups:
                - default
                - client_billing_address
        city:
            groups:
                - default
                - client_billing_address
        country:
            groups:
                - default
                - client_billing_address
        vatId:
            groups:
                - default
                - client_billing_address
        companyName:
            groups:
                - default
                - client_billing_address
    associations: {  }
    callbacks: {  }
