WellCommerce\Bundle\ClientBundle\Entity\ClientDetails:
    fields:
        discount:
            groups:
                - default
                - client_details
        username:
            groups:
                - default
                - client_details
        conditionsAccepted:
            groups:
                - default
                - client_details
        newsletterAccepted:
            groups:
                - default
                - client_details
