# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

doctrine:
    orm:
        resolve_target_entities:
            WellCommerce\Bundle\ClientBundle\Entity\ClientInterface: WellCommerce\Bundle\ClientBundle\Entity\Client

well_commerce_doctrine:
    configuration:
        client:
            manager: WellCommerce\Bundle\ClientBundle\Manager\ClientManager
            factory: WellCommerce\Bundle\ClientBundle\Factory\ClientFactory
            repository: WellCommerce\Bundle\ClientBundle\Repository\ClientRepository
            mapping: "@WellCommerceClientBundle/Resources/config/doctrine/Client.orm.yml"
            entity: WellCommerce\Bundle\ClientBundle\Entity\Client
        client_billing_address:
            factory: WellCommerce\Bundle\ClientBundle\Factory\ClientBillingAddressFactory
            mapping: "@WellCommerceClientBundle/Resources/config/doctrine/ClientBillingAddress.orm.yml"
            entity: WellCommerce\Bundle\ClientBundle\Entity\ClientBillingAddress
        client_details:
            factory: WellCommerce\Bundle\ClientBundle\Factory\ClientDetailsFactory
            mapping: "@WellCommerceClientBundle/Resources/config/doctrine/ClientDetails.orm.yml"
            entity: WellCommerce\Bundle\ClientBundle\Entity\ClientDetails
        client_contact_details:
            factory: WellCommerce\Bundle\ClientBundle\Factory\ClientContactDetailsFactory
            mapping: "@WellCommerceClientBundle/Resources/config/doctrine/ClientContactDetails.orm.yml"
            entity: WellCommerce\Bundle\ClientBundle\Entity\ClientContactDetails
        client_group:
            factory: WellCommerce\Bundle\ClientBundle\Factory\ClientGroupFactory
            repository: WellCommerce\Bundle\ClientBundle\Repository\ClientGroupRepository
            mapping: "@WellCommerceClientBundle/Resources/config/doctrine/ClientGroup.orm.yml"
            entity: WellCommerce\Bundle\ClientBundle\Entity\ClientGroup
        client_group_translation:
            manager: false
            mapping: "@WellCommerceClientBundle/Resources/config/doctrine/ClientGroupTranslation.orm.yml"
            entity: WellCommerce\Bundle\ClientBundle\Entity\ClientGroupTranslation
        client_shipping_address:
            factory: WellCommerce\Bundle\ClientBundle\Factory\ClientShippingAddressFactory
            mapping: "@WellCommerceClientBundle/Resources/config/doctrine/ClientShippingAddress.orm.yml"
            entity: WellCommerce\Bundle\ClientBundle\Entity\ClientShippingAddress
        client_wishlist:
            manager: WellCommerce\Bundle\ClientBundle\Manager\ClientWishlistManager
            factory: WellCommerce\Bundle\ClientBundle\Factory\ClientWishlistFactory
            repository: WellCommerce\Bundle\ClientBundle\Repository\ClientWishlistRepository
            mapping: "@WellCommerceClientBundle/Resources/config/doctrine/ClientWishlist.orm.yml"
            entity: WellCommerce\Bundle\ClientBundle\Entity\ClientWishlist

